import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hasibur Rahman</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h3 className="bg-gray-300 font-mont">Hello</h3>
      </main>
    </>
  );
}
